Add JS and Wasm targets
adamglin0/compose-phosphor-icon pull request #4
Opened 2024-11-11 15:57 UTC by Skaldebane

Adds JS and Wasm targets, samples, and README updates.

2024-11-11 16:18 UTC, Skaldebane commented
Sample builds took too long and my machine ran out of memory, so I couldn't test them unfortunately.
If everything's alright, they should build and run without issues on a better machine.

2024-11-11 23:32 UTC, adamglin0 commented
> Sample builds took too long and my machine ran out of memory, so I couldn't test them unfortunately.
> If everything's alright, they should build and run without issues on a better machine.

I will test it.

2024-11-12 01:03 UTC, adamglin0 requested changes
WASM and JS works good (after add output setting)
![image](https://github.com/user-attachments/assets/1305d2a1-b505-4928-8405-a08141527dc0)

2024-11-12 01:03 UTC, adamglin0 commented on sample/shared/build.gradle.kts
> +        browser()
need output setting. 
e.g.
```
browser {
            commonWebpackConfig {
                outputFileName = "sharedApp.js"
            }
        }
```

2024-11-12 01:03 UTC, adamglin0 commented on sample/shared/build.gradle.kts
> +        browser()
```
browser {
            commonWebpackConfig {
                outputFileName = "sharedApp.js"
            }
        }
```

2024-11-12 01:45 UTC, Skaldebane commented on sample/shared/build.gradle.kts
> +        browser()
ah yeah, i initially thought these extra settings were only for source maps.

2024-11-12 01:54 UTC, adamglin0 approved these changes
LGTM!

2024-11-12 01:57 UTC, merged